import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Blob from "../components/BlobBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className="bg-gray-50 min-h-screen flex flex-col">
          <Blob/>
          <Navbar/>
          <main className="container mx-auto p-4 grow flex items-center justify-center">{children}</main>
          <Footer/>
        </body>
      </html>
    );
}
